# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

minp <- function(x) {
    .Call(`_tsibble_minp`, x)
}

any_not_equal_to_c <- function(x, c) {
    .Call(`_tsibble_any_not_equal_to_c`, x, c)
}

