# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

diff_cpp <- function(x, lag, differences, fill) {
    .Call(`_tsibble_diff_cpp`, x, lag, differences, fill)
}

rle_lgl <- function(x) {
    .Call(`_tsibble_rle_lgl`, x)
}

gcd_interval <- function(x) {
    .Call(`_tsibble_gcd_interval`, x)
}

any_not_equal_to_c <- function(x, c) {
    .Call(`_tsibble_any_not_equal_to_c`, x, c)
}

is_descending <- function(x) {
    .Call(`_tsibble_is_descending`, x)
}

is_ascending <- function(x) {
    .Call(`_tsibble_is_ascending`, x)
}

